const CHARACTERS = {
    LOAD: 'CHARACTERS_LOAD',
    LOAD_SUCCESS: 'LOAD_SUCCESS', 
    LOAD_FAIL: 'CHARACTERS_LOAD_FAIL',   
}

const DETAILS = {
    LOAD: 'DETAILS_LOAD',
    LOAD_SUCCESS: 'DETAILS_SUCCESS', 
    LOAD_FAIL: 'DETAILS_LOAD_FAIL',
    ADD: 'ADD_TO_DETAILS',
    REMOVE: 'REMOVE_TO_DETAILS',
    GO: 'DETAILS_GO',
    CLEAR: 'DETAILS_CLEAR_IDS',   
}

const FILTERS = {
    ACTIVE: 'FILTERS_ACTIVE',
    INACTIVE: 'FILTERS_INACTIVE',
    SEARCH: 'CHARACTERS_SEARCH',
    LOAD_SUCCESS: 'FILTERS_LOAD_SUCCESS'
}

const SUBTITLE = {
    SET: 'SUBTITLE_SET'
}

export { CHARACTERS, DETAILS, SUBTITLE, FILTERS }