const CHARACTERS = {
    LOAD: 'CHARACTERS_LOAD',
    LOAD_SUCCESS: 'LOAD_SUCCESS', 
    LOAD_FAIL: 'CHARACTERS_LOAD_FAIL'
}

const DETAILS = {
    LOAD: 'DETAILS_LOAD',
    LOAD_SUCCESS: 'DETAILS_SUCCESS', 
    LOAD_FAIL: 'DETAILS_LOAD_FAIL',
    ADD: 'ADD_TO_DETAILS',
    REMOVE: 'REMOVE_TO_DETAILS',
    GO: 'DETAILS_GO',
    CLEAR: 'DETAILS_CLEAR_IDS'
}

export { CHARACTERS, DETAILS }